---
title: Get ds by subject for experimental data
subtitle: 
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: cerulean
    code_folding: hide
---

Load packages
```{r setup, message = FALSE}
library(tidyverse)
library(knitr)
library(feather)
library(lubridate)
library(forcats)
library(stringr)
library(langcog)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, cache = F, tidy = F)

theme_set(theme_minimal())
```

constants
```{r}
AVG_MONTH <-  12.0/ 365.2425
```

```{r}
file_1 <- "../../data-flurry/fendle-processed-06-12-17.csv"
file_2 <- "../../data-flurry/fendle-processed-07-12-17.csv"
file_3 <- "../../data-flurry/fendle-processed-12-9-16.csv"

raw_data <- c(file_1, file_2, file_3) %>%
    map_df(read_csv) 

clean_data <- raw_data %>%
    rename(sub_id = SubjectID,
           correct = `CorrectFirstTry?`,
           trial_type = TrialType,
           stage_type = StageType,
           object = Object,
           help = FoxAssistance,
           end_time = EndTime,
           start_time = StartTime,
           resp_start_time = ResponsiveStartTime) %>%
    mutate_at(vars(sub_id, correct, trial_type, stage_type, object, help), funs(as.factor)) %>%
    mutate(start_time = ifelse(nchar(start_time) == 24, str_sub(start_time, 10, -8), 
                               str_sub(start_time, 8, -8)),
           start_time = parse_date_time(start_time, "HMS"),
           end_time = ifelse(nchar(end_time) == 24, str_sub(end_time, 10, -8), 
                               str_sub(end_time, 8, -8)),
           end_time = parse_date_time(end_time, "HMS"),
           resp_start_time = ifelse(nchar(resp_start_time) == 24,
                                    str_sub(resp_start_time, 10, -8), 
                               str_sub(resp_start_time, 8, -8)),
           resp_start_time = parse_date_time(resp_start_time, "HMS"),
           log_trial_time = log(as.numeric(end_time - start_time)),
           trial_type = fct_relevel(trial_type,"FF", "NF", "C-NF", "NN", "C-NN"))

subsetted_data <- clean_data %>%
  filter(!is.na(correct), 
         help == "None") 

```

## Accuracy

### Overall
```{r}
demo <- read_csv("demographics.csv") # note this is incomplete

mss <- subsetted_data %>%
  group_by(trial_type, sub_id) %>%
  summarise(correct = mean(correct == "Y"), 
            n = n()) 

ms <- mss %>%
  group_by(trial_type) %>%
  multi_boot_standard(col = "correct", na.rm = TRUE)

ggplot(ms, aes(x = trial_type, y = mean)) + 
  geom_pointrange(aes(ymin = ci_lower, 
                      ymax = ci_upper)) + 
  geom_hline(yintercept = .5, lty = 2) + 
  ylim(0,1) 
```


### By age
```{r}
demo <- read_csv("demographics.csv") # note this is incomplete

mss <- subsetted_data %>%
  group_by(trial_type, sub_id) %>%
  summarise(correct = mean(correct == "Y"), 
            n = n()) %>%
  left_join(demo) %>%
  filter(!is.na(age)) %>%
    filter(age < 4)  %>%
  mutate(age_bin = cut(age, 4),
         vocab_bin = cut(vocab_acc, 4),
         age_bin2 = as.factor(ntile(age, 4)),
         vocab_bin2 = as.factor(ntile(vocab_acc, 4)))

ms <- mss %>%
  group_by(trial_type, age_bin) %>%
  multi_boot_standard(col = "correct", na.rm = TRUE)

ggplot(ms, aes(x = trial_type, y = mean, group = age_bin, color = age_bin)) + 
  geom_pointrange(aes(ymin = ci_lower, 
                      ymax = ci_upper)) + 
  geom_hline(yintercept = .5, lty = 2) + 
  ylim(0,1) 
```

### By vocab
```{r}
ms <- mss %>%
  group_by(trial_type, vocab_bin) %>%
  multi_boot_standard(col = "correct", na.rm = TRUE)

ggplot(ms, aes(x = trial_type, y = mean, group = vocab_bin, color = vocab_bin)) + 
  geom_pointrange(aes(ymin = ci_lower, 
                      ymax = ci_upper)) + 
  geom_hline(yintercept = .5, lty = 2) + 
  ylim(0,1) 
```


## RTs

### Overall
```{r}
ggplot(subsetted_data, aes(x = log_trial_time)) +
  geom_histogram()

msst <- subsetted_data %>%
  group_by(trial_type, sub_id) %>%
  summarise(mean_trial_time = mean(log_trial_time)) %>%
  left_join(demo) %>%
  filter(!is.na(age)) %>%
  filter(age < 4)  %>%
  mutate(age_bin = cut(age, 4),
         vocab_bin = cut(vocab_acc, 4),
         age_bin2 = as.factor(ntile(age, 4)),
         vocab_bin2 = as.factor(ntile(vocab_acc, 4)))

mst <- msst %>%
  group_by(trial_type) %>%
  multi_boot_standard(col = "mean_trial_time", na.rm = TRUE)

ggplot(mst, aes(x = trial_type, y = mean)) + 
  geom_pointrange(aes(ymin = ci_lower, 
                      ymax = ci_upper))+
  ylim(.7, 1.5)

```

### By age
```{r}
ms <- msst %>%
  group_by(trial_type, age_bin) %>%
  multi_boot_standard(col = "mean_trial_time", na.rm = TRUE)

ggplot(ms, aes(x = trial_type, y = mean, group = age_bin, color = age_bin)) + 
  geom_pointrange(aes(ymin = ci_lower, 
                      ymax = ci_upper))+
  ylim(.75, 1.45)
```

```{r}
ms <- msst %>%
  group_by(trial_type, age_bin2) %>%
  multi_boot_standard(col = "mean_trial_time", na.rm = TRUE)

ggplot(ms, aes(x = trial_type, y = mean, group = age_bin2, color = age_bin2)) + 
  geom_pointrange(aes(ymin = ci_lower, 
                      ymax = ci_upper))+
  ylim(.75, 1.45)
```

### By vocab
```{r}
ms <- msst %>%
  group_by(trial_type, vocab_bin) %>%
  multi_boot_standard(col = "mean_trial_time", na.rm = TRUE)

ggplot(ms, aes(x = trial_type, y = mean, group = vocab_bin, color = vocab_bin)) + 
  geom_pointrange(aes(ymin = ci_lower, 
                      ymax = ci_upper))+
  ylim(.75, 1.45)
```

```{r}
ms <- msst %>%
  group_by(trial_type, vocab_bin2) %>%
  multi_boot_standard(col = "mean_trial_time", na.rm = TRUE)

ggplot(ms, aes(x = trial_type, y = mean, group = vocab_bin2, color = vocab_bin2)) + 
  geom_pointrange(aes(ymin = ci_lower, 
                      ymax = ci_upper))+
  ylim(.75, 1.45)
```

### rt by age
```{r}

msst <- subsetted_data %>%
  group_by(sub_id, trial_type) %>%
  summarise(mean_trial_time = mean(log_trial_time)) %>%
  left_join(demo) %>%
  filter(!is.na(age)) %>%
  filter(age < 4) 

ggplot(msst, aes(x = age, y = mean_trial_time, color = trial_type)) + 
  #geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~trial_type)

```

## Make effect sizes by binning 
```{r}
## by subjects doesn't work (not enough var)
m = subsetted_data %>%
  filter(trial_type == "NF") %>%
  group_by(trial_type, sub_id) %>%
  mutate(correct = ifelse(correct == "Y", 1, 0)) %>%
  summarize(sd = sd(correct),
           correct = mean(correct),
           n = n()) %>%
  mutate(sd = ifelse(sd == 0, .00001, sd),
         d = (correct-.5)/sd)

essA = subsetted_data %>%
  filter(trial_type == "NF") %>%
  group_by(trial_type, sub_id) %>%
  mutate(correct = ifelse(correct == "Y", 1, 0)) %>%
  summarize(correct = mean(correct),
            n = n()) %>%
  left_join(demo) %>%
  mutate(age = age*12) %>%
  filter(!is.na(age)) %>%
  mutate(age_bin = cut(age, 20)) %>%
  group_by(age_bin) %>%
  summarize(sd = sd(correct),
            correct = mean(correct),
            n = n(),
            mean_age = mean(age)) %>%
  mutate(d = (correct-.5)/sd) %>%
  filter(is.finite(d))

ggplot(essA, aes(x = mean_age, y = d, group = 1)) + 
  geom_point(aes(size = n)) +
  geom_smooth(method = "lm", formula = y ~ log(x))
```

```{r}

essV = subsetted_data %>%
  filter(trial_type == "NF") %>%
  group_by(trial_type, sub_id) %>%
  mutate(correct = ifelse(correct == "Y", 1, 0)) %>%
  summarize(correct = mean(correct),
            n = n()) %>%
  left_join(demo) %>%
  filter(!is.na(age)) %>%
  mutate(vocab_bin = cut(vocab_acc, 20)) %>%
  group_by(vocab_bin) %>%
  summarize(sd = sd(correct),
            correct = mean(correct),
            n = n(),
            mean_vocab = mean(vocab_acc)) %>%
  mutate(d = (correct-.5)/sd) %>%
  filter(is.finite(d))

ggplot(essV, aes(x = mean_vocab, y = d, group = 1)) + 
  geom_point(aes(size = n)) +
  geom_smooth(method = "lm", formula = y ~ log(x))
```

```{r}
write_csv(essA, "experimental_es_by_age.csv")
write_csv(essV, "experimental_es_by_vocab.csv")

```

