---
title: ME MA outliers
subtitle: 
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: cerulean
    code_folding: hide
---


```{r setup, message = FALSE, echo = FALSE, warning = FALSE}
library(tidyverse)
library(knitr)
library(metafor)
library(here)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, cache = F, tidy = F)

theme_set(theme_minimal())
```

In response to reviewer 1. 
```{r}
ME_DATA_PATH <- here("data/0_metaanalysis_data.csv")
ma_raw <- read_csv(ME_DATA_PATH) %>%
  select(1:4, 6:8, 10:16, 18,19,21, 27:29, 31:34, 48:50, 59) %>%
  mutate_if(is.character, as.factor)

AVG_MONTH <- 30.43688
ma_c <- ma_raw %>%
  filter(!is.na(d_calc)) %>%
  mutate(mean_age = mean_age_1/AVG_MONTH,
         year = as.numeric(str_sub(short_cite, -5, -2)),
         condition_type = as.factor(ifelse(infant_type == "typical" & ME_trial_type == "FN", "TFN", 
                                 ifelse(infant_type == "typical" & ME_trial_type == "NN", "TNN", 
                                        as.character(infant_type))))) %>%
  filter(mean_age < 144)   #  (12 yo), excludes MR population
  # filter(!(study_ID %in% c("williams2009", "frank1999"))) # for checking that holds when exclude dissertations [it does]
```

# Outliers
```{r}
overall_mean <- mean(ma_c$d_calc)
overall_sd <- sd(ma_c$d_calc)

plus2 <- overall_mean + (2*(overall_sd))
minus2 <- overall_mean - (2*(overall_sd))

plus3 <- overall_mean + (3*(overall_sd))
minus3 <- overall_mean - (3*(overall_sd))

twosd_outliers <- ma_c %>%
  filter(d_calc > plus2 | d_calc < minus2) %>%
  data.frame()

threesd_outliers <- ma_c %>%
  filter(d_calc > plus3 | d_calc < minus3) %>%
  data.frame()

```

There are 8 conditions that are 2sds beyond the mean; There are 3 conditions that are 3sds beyond the mean: 

```{r}
kable(threesd_outliers)
```


# Testing for heteroskedasticity{.tabset}

There's heteroskedasticity if we include the outliers; it goes away if you exclude them. 

## Including outliers:
```{r}
model <- lm(d_calc ~ mean_age, data = ma_c, weights = n_1)
olsrr::ols_test_breusch_pagan(model)
olsrr::ols_test_f(model)
```

## Excluding outliers (3sd beyond mean):
```{r}
model <- lm(d_calc ~ mean_age, data = ma_c  %>% filter(d_calc > plus3 | d_calc < minus3), weights = n_1)
olsrr::ols_test_breusch_pagan(model)
olsrr::ols_test_f(model)
```


      
      
