---
title: Most frequent name for ME
subtitle: 
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: cerulean
    code_folding: hide
---

Load packages
```{r setup, message = FALSE}
library(tidyverse)
library(knitr)
library(feather)
library(lubridate)
library(forcats)
library(stringr)
library(langcog)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, cache = F, tidy = F)

theme_set(theme_minimal())
```

```{r}
ME_DATA_PATH <- here("data/0_metaanalysis_data.csv")
ma_raw <- read_csv(ME_DATA_PATH) %>%
  select(c(1:3, 6, 9, 12, 14, 15, 18, 20, 22:24, 26,
           29:30, 49, 51:53, 95:99, 100, 102:103)) %>%
  mutate_if(is.character, as.factor)

AVG_MONTH <- 30.43688
ma_c <- ma_raw %>%
  filter(!is.na(d_calc)) %>%
  mutate(mean_age = mean_age_1/AVG_MONTH,
         year = as.numeric(str_sub(short_cite, -5, -2)),
         condition_type = as.factor(ifelse(infant_type == "typical" & ME_trial_type == "FN", "TFN", 
                                 ifelse(infant_type == "typical" & ME_trial_type == "NN", "TNN", 
                                        as.character(infant_type))))) %>%
  filter(mean_age < 144)   #  (12 yo), excludes MR population
  # filter(!(study_ID %in% c("williams2009", "frank1999"))) # for checking that holds when exclude dissertations [it does]
```

```{r}
ME_NAMES_PATH <- here("writeup/journal_paper/response_to_reviewers/ME_names.csv")
#ma_c %>%
#  distinct(long_cite) %>%
#  write_csv(ME_NAMES_PATH)
read_csv(ME_NAMES_PATH) %>%
  count(name) %>%
  filter(name == "disambiguation"|name ==  "me")
```