---
title: Participant nested models
subtitle: 
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: cerulean
    code_folding: hide
---


```{r setup, message = FALSE, echo = FALSE, warning = FALSE}
library(tidyverse)
library(knitr)
library(metafor)
library(here)
library(broom)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, cache = F, tidy = F)

theme_set(theme_minimal())
```

```{r}
ME_DATA_PATH <- here("data/0_metaanalysis_data.csv")
ma_raw <- read_csv(ME_DATA_PATH) %>%
  select(1:4, 6:8, 10:16, 18,19,21, 27:29, 31:34, 48:50, 59) %>%
  mutate_if(is.character, as.factor)

AVG_MONTH <- 30.43688
ma_c <- ma_raw %>%
  filter(!is.na(d_calc)) %>%
  mutate(mean_age = mean_age_1/AVG_MONTH,
         year = as.numeric(str_sub(short_cite, -5, -2)),
         condition_type = as.factor(ifelse(infant_type == "typical" & ME_trial_type == "FN", "TFN", 
                                 ifelse(infant_type == "typical" & ME_trial_type == "NN", "TNN", 
                                        as.character(infant_type))))) %>%
  filter(mean_age < 144)   
```

multilingual data
```{r}
test_data <- filter(ma_c, infant_type == "multilingual")  %>%
  select(2,8,9,10,11,12,13, 26, 27, 29)
DT::datatable(test_data)
```


No grouping by infant
```{r}
model1 <- mono_vs_multi_model <- rma.mv(d_calc ~ mean_age + infant_type, V = d_var_calc,
                      random = ~ 1 | short_cite,
                      method = "REML",
                      data = filter(ma_c, infant_type != 'NT'))

summary(model1)
```

Grouping by infant
```{r}

model2 <- mono_vs_multi_model <- rma.mv(d_calc ~ mean_age + infant_type, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant,
                      method = "REML",
                      data = filter(ma_c, infant_type != 'NT'))
summary(model2)
```

