---
title: Mutual Exclusivity
author: "Mike Frank, Veronica Cristiano, Brenden Lake, Tammy Kwan"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    theme: spacelab
---

```{r}
library(tidyverse)
library(lubridate)
library(langcog)
```

Read in event log. 

```{r}
events <- read_csv("data-flurry/fendle-12-9-16.csv")
```

helper.

```{r}
parse_params <- function(x) {
  json <- str_sub(x$Params, 3, -2)
  splits <- str_split(json, pattern = ";..")[[1]] 

  dx <- splits %>%
    map_df(function(y) {
      ys <- str_split(y, pattern = " : ")[[1]]
      return(data_frame(key = ys[1], value = ys[2]))
    }) %>%
    spread(key, value) %>%
    mutate(event = x$Event,
           version = x$Version)
  
  return(dx)
}
```
  
parse events.

```{r}
d_parsed <- events %>% 
  mutate(event_num = 1:n()) %>%
  split(.$event_num) %>%
  map_df(parse_params)
```

clean up data frame.

```{r}
d <- d_parsed %>%
  rename(sub_id = `Subject ID`,
         user_id = `User ID`,
         end_time = `End Time`,
         start_time = `Start Time`,
         resp_start_time = `Responsive Start Time`,
         stage_id = `Stage ID`,
         stage_type = `Stage Type`,
         correct = `Correct First Try?`,
         help = `Fox Assistance`,
         object = Object,
         category = Category,
         object1 = `Object`,
         time_start = `Time Start`,
         type = Type, 
         trial_type = `Trial Type`) %>%
  select(-user_id, -stage_id) %>%
  mutate(start_time = parse_date_time(str_sub(start_time, 1, -7), "db HMS"),
         end_time = parse_date_time(str_sub(end_time, 1, -7), "db HMS"),
         resp_start_time = parse_date_time(str_sub(resp_start_time, 1, -7), "db HMS")) %>%
  filter(sub_id != " Test2")
  
```

investigate only trials that are actually trials. 

```{r}
mss <- filter(d, !is.na(trial_type)) %>%
  group_by(trial_type, sub_id) %>%
  summarise(correct = mean(correct == "Y"), 
            n = n())

ggplot(mss, aes(x = correct)) + 
  geom_histogram(binwidth = .25) + 
  facet_wrap(~trial_type)
```

summary

```{r}
ms <- mss %>%
  multi_boot_standard(col = "correct", na.rm = TRUE)

ggplot(ms, aes(x = trial_type, y = mean)) + 
  geom_pointrange(aes(ymin = summary_ci_lower, 
                      ymax = summary_ci_upper)) + 
  geom_hline(yintercept = .5, lty = 2) + 
  ylim(0,1) 
```

  
```